export enum Service {
  DEFAULT_MESSAGE_BUS = 'messenger_DEFAULT_MESSAGE_BUS',
  AMQP_MESSAGE_BUS = 'messenger_AMQP_MESSAGE_BUS',
  MESSAGE_HANDLERS = 'messenger_MESSAGE_HANDLERS',
  MESSAGE_HANDLERS_REGISTRY = 'messenger_MESSAGE_HANDLERS_REGISTRY',
  CHANNEL_REGISTRY = 'messenger_CHANNEL_REGISTRY',
  CHANNELS = 'messenger_CHANNELS',
  LOGGER = 'messenger_LOGGER',
}
