name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workspace:
          - "@nestjstools/messaging"
          - "@nestjstools/messaging-amazon-sqs-extension"
          - "@nestjstools/messaging-google-pubsub-extension"
          - "@nestjstools/messaging-nats-extension"
          - "@nestjstools/messaging-rabbitmq-extension"
          - "@nestjstools/messaging-redis-extension"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test --workspace=${{ matrix.workspace }}
